---
description: "Pushes Docker image to GitHub packages"

inputs:
  registry:
    description: "Registry"
    required: false
    default: "ghcr.io"
  registry_username:
    description: "Username for image registry"
    required: false
    default: "mback2k"
  registry_password:
    description: "Password for image registry"
    required: false
    default: ""
  build_args:
    description: "Build arguments"
    required: false
    default: ""
  image_name:
    description: "Image name"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v1

    - shell: bash
      id: name
      run: echo "::set-output name=image::${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image_name }}" | sed 's:/*$::'

    - shell: bash
      id: repo
      run: echo "::set-output name=description::$(git describe --always --tags)"

    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: ${{ steps.name.outputs.image }}
        tags: |
          type=raw,value=${{ steps.repo.outputs.description }}
          type=raw,value=latest
          type=ref,event=branch
          type=ref,event=tag

    - uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: ${{ inputs.build_args }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
...
