---
description: "Pushes Docker image to GitHub packages"

inputs:
  registry:
    description: "Registry"
    required: false
    default: "ghcr.io"
  registry_username:
    description: "Username for image registry"
    required: false
    default: "mback2k"
  registry_password:
    description: "Password for image registry"
    required: false
    default: "${{ secrets.GITHUB_TOKEN }}"
  build_args:
    description: "Build arguments"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v1

    - run: "git describe --always --tags"
      id: tags

    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: "${{ inputs.registry }}/${{ github.repository }}"

    - uses: docker/login-action@v1
      if: github.event_name != "pull_request"
      with:
        username: "${{ inputs.registry }}"
        username: "${{ inputs.registry_username }}"
        password: "${{ inputs.registry_password }}"
        build-args: "${{ inputs.build_args }}"

    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "${{ steps.meta.outputs.tags + tags }}"
        labels: "${{ steps.meta.outputs.labels }}"
...
